## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN", "NAME"])

In [3]:
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ["T25", "T14", "T29", "T15", "T17"]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
count = application_df['CLASSIFICATION'].value_counts()
count[count>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = ["C7120","C1500",
                              "C1800","C6000","C1250","C8200","C1238","C1278","C1235","C1237","C7210",
                              "C2400","C1720","C4100","C1257","C1600","C1260","C2710","C0","C3200",
                              "C1234","C1246","C1267","C1256","C1370","C1236","C2190","C4200","C5200",
                              "C1248","C2600","C1580","C6100","C1820","C1900","C2570","C1283","C1570",
                              "C3700","C2500","C1283 ","C2380","C1732","C1728","C2170","C4120","C8210",
                              "C4500","C1245","C2561","C2150"]

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
Other      207
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
Name: CLASSIFICATION, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,0

In [11]:
# Split our preprocessed data into our features and target arrays
X = dummies_df.drop(columns=["IS_SUCCESSFUL"]).values
y = dummies_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [12]:
X.shape

(34299, 63)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=120, activation="relu", input_dim=63))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="tanh"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 120)               7680

 dense_1 (Dense)             (None, 80)                9680

 dense_2 (Dense)             (None, 80)                6480

 dense_3 (Dense)             (None, 1)                 81

=================================================================
Total params: 23,921
Trainable params: 23,921
Non-trainable params: 0
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
## NEED HELP
from keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint("weights.h5", monitor='loss', verbose=1,
    save_weights_only=True, mode='auto', save_freq=5)

In [17]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 7s 6ms/step - loss: 0.5690 - accuracy: 0.7202
Epoch 2/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5555 - accuracy: 0.7271
Epoch 3/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5518 - accuracy: 0.7292
Epoch 4/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5497 - accuracy: 0.7308
Epoch 5/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5471 - accuracy: 0.7317
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5469 - accuracy: 0.7304
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7311
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7338
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7330
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7337
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7342
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5419 - accuracy: 0.7354
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7355
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7351
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7358
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7372
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7378
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5378 - accuracy: 0.7378
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7385
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7365
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7372
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7374
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7390
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7387
Epoch 25/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7392
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7391
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7381
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5347 - accuracy: 0.7393
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7387
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7391
Epoch 31/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5339 - accuracy: 0.7395
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7385
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7395
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7385
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7391
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7395
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7397
Epoch 38/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5321 - accuracy: 0.7403
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7405
Epoch 40/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5321 - accuracy: 0.7398
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7393
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7402
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7407
Epoch 44/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5318 - accuracy: 0.7410
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7416
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7411
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7402
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7419
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7411
Epoch 50/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5309 - accuracy: 0.7413
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5305 - accuracy: 0.7410
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7416
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7410
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7407
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7398
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7413
Epoch 57/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5311 - accuracy: 0.7405
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7410
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7408
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5306 - accuracy: 0.7407
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7413
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7418
Epoch 63/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5295 - accuracy: 0.7418
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.7413
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7419
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7422
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7413
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7414
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7420
Epoch 70/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5291 - accuracy: 0.7418
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7416
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7427
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7408
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7425
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7398
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.7417
Epoch 77/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5300 - accuracy: 0.7414
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7413
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7419
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7421
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7419
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7421
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5288 - accuracy: 0.7427
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7409
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7417
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7422
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7418
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7413
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7429
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5291 - accuracy: 0.7428
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5285 - accuracy: 0.7427
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5281 - accuracy: 0.7431
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7416
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7428
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7416
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7422
Epoch 97/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5285 - accuracy: 0.7414
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5282 - accuracy: 0.7424
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5277 - accuracy: 0.7435
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5283 - accuracy: 0.7419

In [18]:
# Evaluate model for loss and accuracy
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5545 - accuracy: 0.7306 - 787ms/epoch - 3ms/step
Loss: 0.5545156598091125, Accuracy: 0.7306122183799744

In [19]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization1.h5")

In [20]:
# Download HDF5 file
from google.colab import files
files.download("AlphabetSoupCharity_Optimization1.h5")